apiVersion: v1
kind: Service
metadata:
  name: boilerplay
  labels:
    app: boilerplay
spec:
  ports:
  - port: 80
    targetPort: 9000
    name: http
  selector:
    app: boilerplay
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: boilerplay
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: boilerplay
    spec:
      containers:
      - name: app
        image: boilerplay/boilerplay:latest
        ports:
        - containerPort: 9000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: boilerplay-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: boilerplay.com
    http:
      paths:
      - backend:
          serviceName: boilerplay
          servicePort: 9000
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: boilerplay
  name: boilerplay-config
data:
  application.conf: |
    foo = "bar"
---
